alias commit="git commit"
alias push="git push origin master"
alias amend="git commit --amend --no-edit"
alias db="sudo su postgres"
alias start="source envs/simple-folder/ecom-env/bin/activate && cd envs/simple-folder/hustle_ecommerce/"
alias run="python manage.py runserver"
alias gs="git status"
alias gd="git diff"
